### ISSUE TITLE
Sign up/in

### ISSUE THREAD

**Issue by wendsday** [wendsday/mothership#2]
Fields:
- Email
- Password
- "View Password" option

**Comment by wendsday** [comment]
### Splash
![logged out](https://cloud.githubusercontent.com/assets/840674/18813365/acae719e-82ac-11e6-9759-314f292db13e.png)
---
### Login
![logged out copy 2](https://cloud.githubusercontent.com/assets/840674/18813363/acaabf4a-82ac-11e6-8d0d-2df872f70e49.png)
---
### Signup
![logged out copy 4](https://cloud.githubusercontent.com/assets/840674/18813387/5201527e-82ad-11e6-8ec5-f0826bbd5100.png)
---
### Brew form with signup 
(brew form is not final design, however bottom third of the screen has the intended experience for signup via brew form)
![new tea brew step 1 logged out](https://cloud.githubusercontent.com/assets/840674/18813378/14fffb82-82ad-11e6-8a72-02c5ebe6bd49.png)

**Comment by Timmehs** [comment]
Is it important that the sign up screen be a different color?

**Comment by wendsday** [comment]
@Timmehs Why, is it too hard? It would be nice if it was but not crucial to functionality. I haven't proven its effect on user experience.
